---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-7 BEAKER_TESTMODE=apply BEAKER_keycloak_full=true
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-7 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1 BEAKER_keycloak_full=true
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-7 BEAKER_TESTMODE=apply BEAKER_keycloak_full=true
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-7 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1 BEAKER_keycloak_full=true
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-8 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-8 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-8 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-8 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-9 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-9 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-9 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-9 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1804 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1804 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1804 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: xenial
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1804 BEAKER_TESTMODE=apply BEAKER_keycloak_version=8.0.1
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
    -
      env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
      rvm: 2.4.5
      stage: spec
    -
      env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"
      rvm: 2.5.3
      stage: spec
  allow_failures:
    -
      env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 5" FIXTURES_YML=".fixtures-latest.yml"
      rvm: 2.4.5
    -
      env: CHECK="parallel_spec" PUPPET_GEM_VERSION="~> 6" FIXTURES_YML=".fixtures-latest.yml"
      rvm: 2.5.3
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: treydock@gmail.com
deploy:
  provider: puppetforge
  user: treydock
  password:
    secure: "u4N3WOhiO4X0mmEF7I+ARGpcw4Wrmt1xA8cmG2Qlnvr+r3c7RgWfc6GoabLicGKoN/OqVPD1b6lXJ+Xrg8VAJb9NmFjXYkowbTYgyyPsx6fSIshaquThkrEUsaF1C5hWx1rADXCz8hkpvX537xye/uKQlvDjwHyHaJWu3rpCfsDApYwYZhIkKtsSk2hOlcX9jfI1LE/H6YYo44uRBxg2lyUusScJQcDe023mBYOOSet3C4w4UpPBqR0mu9XvjJHk0KJzBE2Jk6g7W+02/ZkVW9qDXh70mCE562uQN/CE8rjcM5V1M6L69YzG5rv0LSuV4rnrjNtkNz6GZPDKIpuwOLEkA0M+jBr+F2d4tPHyMVDGLQHIIl5/TxXU2A9+gDe9yZFeZ7KEOSkkYfEgKgHcPHMZQJhs7Xkj2ab+F3AFjrSbjWngX892NQXp9XK4EXBZzogdsEp+wHULc9ybb9BKUNS0FIbCOjJoqBuwe7Is8vfVQ+OXAxVnP1POEoAgmgD3gQVHtedBAYrT7Ge+uxILua+KaPYkxBh/Cg9TYYSJeO/y0LH8pV3zSOQ3oU3MGZRbZrLbNkFAq9sYu3Klw52NEgfgXNRaE5AIpC0Tjf/BHZuaGGPyZML4A14tctwzFCFmG8SXkN2fFtpS5LAfLzbizi2KecPMyEjSpHJATJ/6HuQ="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
