---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.1.6
      sudo: required
      services: docker
      env: BEAKER_set="centos-6-x64-docker" PUPPET_INSTALL_VERSION=3.8.6 PUPPET_INSTALL_TYPE=foss
      bundler_args:
      script: sudo service docker restart ; sleep 10 ; bundle exec rake beaker
    - rvm: 2.1.6
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-x64-docker" PUPPET_INSTALL_VERSION=3.8.6 PUPPET_INSTALL_TYPE=foss
      bundler_args:
      script: sudo service docker restart ; sleep 10 ; bundle exec rake beaker
notifications:
  email: false
