---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake release_checks
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.2
      env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.1
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-x64-docker"
      bundler_args:
      script: sudo service docker restart ; sleep 10 ; bundle exec rake beaker
    - rvm: 2.4.1
      sudo: required
      services: docker
      env: BEAKER_set="debian-9-docker"
      bundler_args:
      script: sudo service docker restart ; sleep 10 ; bundle exec rake beaker
notifications:
  email: false
