name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.4.9
            puppet: 5
            fixtures: .fixtures.yml
            allow_failure: false
          - ruby: 2.5.7
            puppet: 6
            fixtures: .fixtures.yml
            allow_failure: false
          - ruby: 2.4.9
            puppet: 5
            fixtures: .fixtures-latest.yml
            allow_failure: true
          - ruby: 2.5.7
            puppet: 6
            fixtures: .fixtures-latest.yml
            allow_failure: true
    env:
      BUNDLE_WITHOUT: system_tests:release
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
      FACTER_GEM_VERSION: "< 4.0"
      FIXTURES_YML: ${{ matrix.fixtures }}
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Validate
        run: bundle exec rake check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint
      - name: Run tests
        run: bundle exec rake parallel_spec
  acceptance:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        set:
          - "centos-7"
          - "centos-8"
          - "debian-9"
          - "debian-10"
          - "ubuntu-1804"
        puppet:
          - "puppet5"
          - "puppet6"
        keycloak_version:
          - "8.0.1"
          - "10.0.1"
        keycloak_full:
          - "no"
        include:
          - set: "centos-7"
            puppet: "puppet5"
            keycloak_version: "8.0.1"
            keycloak_full: "yes"
          - set: "centos-7"
            puppet: "puppet5"
            keycloak_version: "10.0.1"
            keycloak_full: "yes"
          - set: "centos-7"
            puppet: "puppet6"
            keycloak_version: "8.0.1"
            keycloak_full: "yes"
          - set: "centos-7"
            puppet: "puppet6"
            keycloak_version: "10.0.1"
            keycloak_full: "yes"
    env:
      BUNDLE_WITHOUT: development:release
      BEAKER_debug: true
    name: ${{ matrix.puppet }} ${{ matrix.set }} (keycloak=${{ matrix.keycloak_version }} full=${{ matrix.keycloak_full }})
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: apparmor
        run: |
            set -x
            sudo apt-get remove mysql-server --purge
            sudo apt-get install apparmor-profiles
            sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake beaker
        env:
          BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet }}
          BEAKER_set: ${{ matrix.set }}
          BEAKER_keycloak_version: ${{ matrix.keycloak_version }}
          BEAKER_keycloak_full: ${{ matrix.keycloak_full }}
